apiVersion: apps/v1
kind: Deployment
metadata:
  name: vk-integration
  labels:
    app: vk-integration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vk-integration
  template:
    metadata:
      labels:
        app: vk-integration
    spec:
      containers:
        - name: app
          image: salving/vk-integration:0.0.1
          ports:
            - containerPort: 8080
          imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: vk-integration
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
